Update Prepare prebuild environment.yml

diff --git a/.github/workflows/Prepare prebuild environment.yml b/.github/workflows/Prepare prebuild environment.yml
--- a/.github/workflows/Prepare prebuild environment.yml
+++ b/.github/workflows/Prepare prebuild environment.yml
@@ -352,19 +352,19 @@ jobs:
           npm ci --ignore-scripts
           npm run build
 
-    - name: Check Release prebuilds exist
-      shell: bash
-      run: |
-        fileCount=$(ls prebuilds/*/node-pty*tar.gz | wc -l)
-        echo "Release Prebuild count ${fileCount}"
-        if [ "$fileCount" -ne ${ReleasePrebuildCount} }} ]; then echo "::error::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; exit 1; else echo "::notice::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; fi
+      - name: Check Release prebuilds exist
+        shell: bash
+        run: |
+          fileCount=$(ls prebuilds/*/node-pty*tar.gz | wc -l)
+          echo "Release Prebuild count ${fileCount}"
+          if [ "$fileCount" -ne ${ReleasePrebuildCount} }} ]; then echo "::error::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; exit 1; else echo "::notice::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; fi
 
-  - name: Check Release prebuildify`s exist
-      shell: bash
-      run: |
-        fileCount=$(ls prebuilds/*/node-pty*tar.gz | wc -l)
-        echo "Release Prebuild count ${fileCount}"
-        if [ "$fileCount" -ne ${ReleasePrebuildifyCount} }} ]; then echo "::error::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildifyCount}"; exit 1; else echo "::notice::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildifyCount}"; fi
+      - name: Check Release prebuildify`s exist
+        shell: bash
+        run: |
+          fileCount=$(ls prebuilds/*/node-pty*tar.gz | wc -l)
+          echo "Release Prebuild count ${fileCount}"
+          if [ "$fileCount" -ne ${ReleasePrebuildifyCount} }} ]; then echo "::error::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; exit 1; else echo "::notice::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; fi
 
       - name: get-npm-version
         id: package-version
